### ISSUE TITLE
shows a blank page when i use this code

### ISSUE THREAD

**Issue by lsuresh-k** [sathyamoorthi/ember-play#1]
isInvalid: function() {
            //if question is prepopulated and there are answers available,
            //make sure button is enabled
            if (this.get('buttonIsActive')) {
                return true;
            }
            if ( this.get('selected') || this.get('answer') ){
                if (Ember.isArray(this.get('selected'))) {
                    return !this.get('selected').mapBy(function (choice) {
                        if (typeof choice === 'object') {
                            console.log(choice);
                            return choice.selected;
                        }
                        return true;
                    }).length;
                }
                return false;
            }

**Comment by sathyamoorthi** [comment]
Hi @lav27. Seems this code is not a part of this sample project. If you have trouble in your own code, please get a help from Sackoverflow.
